# Generated by Django 5.2.3 on 2025-07-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, default='N/A', max_length=100, verbose_name='Model Name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload a picture of the vehicle. If left blank, a default image will be used based on vehicle type.', null=True, upload_to='vehicle_pics/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('HEAVY', 'HEAVY'), ('LIGHT', 'LIGHT')], max_length=50),
        ),
    ]
