# Generated by Django 5.2.3 on 2025-07-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_vehicle_model_vehicle_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text='The current physical location of the vehicle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_at_location', to='booking_app.location', verbose_name='Current Location'),
        ),
    ]
