# Generated by Django 5.2.3 on 2025-07-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_vehicle_current_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload a picture of the vehicle.', null=True, upload_to='vehicle_pics/', verbose_name='Picture'),
        ),
    ]
